notify-update:
  # Notifies Plugin Updates
  enable: true
tablist:
  enable: false
  header: '&6Server'
  footer: '&6{0}&7/&6{1}'
pvp:
  # true = '/pvp' is ignored
  # false = '/pvp' allowed if permission is set
  world: false
  world_nether: false
  world_the_end: false
  other_world: false
  pvp_world: true
economy:
  currency: $
  format: '#,##0.00'
  starting-balance: 0.0
homes:
  # default max homes on file setup
  default: 1
  # per home cost
  cost: 750.0
deaths:
  drop-player-head:
    # enable drop player heads
    enable: true
    # chance of the drop
    chance: 30
connection:
  join:
    # if false permission: smpcore.join-message
    enable: true
    message: '{0}&e has joined the server [&a+&e]'
    sound:
      enable: true
      type: ENTITY_FOX_AMBIENT
      volume: 0.75F
      pitch: 1.0F
  quit:
    # if false permission: smpcore.quit-message
    enable: true
    message: '{0}&e has left the server [&c-&e]'
    sound:
      enable: true
      type: ENTITY_FOX_AMBIENT
      volume: 0.75F
      pitch: 1.0F
commands:
  cooldown:
    # cooldown for rank commands
    # these are the only ones which are able to get cooldown
    feed: 120
    heal: 120
    repair: 3600
  disable:
    - icanhasbukkit
    - version
    - about
    - me
    - stop
    - reload
notification:
  # Permissions
  # smpcore.notify.block-break
  # smpcore.notify.bucket-empty
  # smpcore.notify.block-place
  #
  # Placeholders
  # {0} Player, {1} Material
  # {2} World, {3} X, {4} Y, {5} Z
  enable: true
  block-break:
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
    - ANCIENT_DEBRIS
    - MATERIAL_NAME
  bucket-empty:
    - LAVA_BUCKET
    - MATERIAL_NAME
  block-place:
    - TNT
    - MATERIAL_NAME
  message:
    - '&7---------------'
    - '&cDetected: &f{0}'
    - '&cMaterial: &f{1}'
    - '&cLocation:'
    - '&cWorld:&f {2} &cX: &f{3} &cY: &f{4} &cZ: &f{5}'
    - '&7---------------'
